server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # SimplePro API logs
  - job_name: simplepro-api
    static_configs:
      - targets:
          - localhost
        labels:
          job: simplepro-api
          environment: production
          __path__: /var/log/simplepro/api/*.log

  # SimplePro Web logs
  - job_name: simplepro-web
    static_configs:
      - targets:
          - localhost
        labels:
          job: simplepro-web
          environment: production
          __path__: /var/log/simplepro/web/*.log

  # System logs
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          __path__: /var/log/syslog

  # Docker container logs
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
