name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger

jobs:
  # Security vulnerability check
  security-check:
    name: Security Vulnerability Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm audit --audit-level=moderate

      - name: Generate security report
        run: |
          npm audit --json > security-audit.json
          echo "## Security Audit Report" > security-report.md
          echo "Generated on: $(date)" >> security-report.md
          echo "" >> security-report.md
          npm audit --human-readable >> security-report.md

      - name: Upload security report
        uses: actions/upload-artifact@v3
        with:
          name: security-audit-report
          path: |
            security-audit.json
            security-report.md

      - name: Create issue if vulnerabilities found
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            const title = 'Security vulnerabilities detected';
            const body = `
            Security vulnerabilities have been detected in the dependencies.

            Please review the security audit report and update the affected packages.

            Generated on: ${new Date().toISOString()}
            Commit: ${context.sha}

            To view the full report, check the workflow artifacts.
            `;

            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['security', 'dependencies']
            });

  # Dependency updates
  dependency-update:
    name: Update Dependencies
    runs-on: ubuntu-latest
    needs: security-check

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Update dependencies
        run: |
          # Update patch and minor versions
          npx npm-check-updates -u --target minor
          npm install

      - name: Run tests after update
        run: |
          npm run lint
          npm run test

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'Automated dependency updates'
          body: |
            This PR contains automated dependency updates.

            ### Changes
            - Updated patch and minor versions of dependencies
            - All tests are passing

            ### Review Notes
            - Please review the changes carefully
            - Check for any breaking changes in the updated packages
            - Ensure all functionality works as expected

            Generated by GitHub Actions on: ${{ github.run_id }}
          branch: automated/dependency-updates
          delete-branch: true
